### ISSUE TITLE
PYTHONOPTIMIZE=2 breaks zope.component.Interface

### ISSUE THREAD

**Issue by teythoon** [zopefoundation/zope.component#67]
### What I did:

Trying to reduce the memory consumption of Mailman3 which uses Zope.  Turns out that dropping docstrings reduces the memory usage by around 10%, which amounts to ~100MB on 64 bit Python.  However, this breaks in Zope. 

```sh
% python -c "from zope.component import Interface"
% PYTHONOPTIMIZE=1 python -c "from zope.component import Interface"
% PYTHONOPTIMIZE=2 python -c "from zope.component import Interface"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.10/site-packages/zope/component/__init__.py", line 37, in <module>
    from zope.component.globalregistry import getGlobalSiteManager
  File "/tmp/venv/lib/python3.10/site-packages/zope/component/globalregistry.py", line 63, in <module>
    def getGlobalSiteManager():
  File "/tmp/venv/lib/python3.10/site-packages/zope/component/interfaces.py", line 378, in inherits_arch_docs
    return _inherits_docs(func, IComponentArchitecture)
  File "/tmp/venv/lib/python3.10/site-packages/zope/component/interfaces.py", line 370, in _inherits_docs
    doc += "\n        .. seealso::"
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

### What I expect to happen:

This not to crash.

### What actually happened:

Crash trying to amend the docstring which is `None` under `PYTHONOPTIMIZE=2`.

### What version of Python and Zope/Addons I am using:

```sh
% uname -a
Linux thinkbox 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux
% python --version
Python 3.10.9
% pip list zope.component
Package        Version
-------------- -------
pip            22.3.1
setuptools     65.5.0
wheel          0.38.4
zope.component 5.0.1
zope.event     4.6
zope.hookable  5.4
zope.interface 5.5.2
```

**Comment by dataflake** [comment]
I just released zope.component version 5.1.0 with the fix.

**Comment by teythoon** [comment]
Thanks for the quick fix and release!
